### ISSUE TITLE
Get selected item in paper-listbox

### ISSUE THREAD

**Issue by vinhtq** [PolymerElements/paper-listbox#10]
I tried to get selected item value but i cannot!

Here is the code:
```
<div class="suggestions">
    <paper-listbox selected="{{selectedLocation}}" attr-for-selected="location">
        <template is="dom-repeat" items="{{suggestions}}">
            <paper-icon-item location="{{item.location}}">
                <iron-icon icon="maps:place" item-icon></iron-icon>
                <div class="location">
                    <h4>{{item.description}}</h4>
                    <p>{{item.subdescription}}</p>
                </div>
            </paper-icon-item>
        </template>
    </paper-listbox>
</div>
```

In script tag:
```
Polymer({
    is: "google-map-search-bar",
    properties: {
        ...
   
        selectedLocation: {
            type: String,
            observer: 'test'
        }
    },
    test: function(newValue, oldValue) {
        console.log(newValue); // Give out undefined
    }
});
```

I tried many ways to get the selected item value but i cannot.

Can you help me if you have another way?

**Comment by bicknellr** [comment]
Hi @vinhtq, I haven't been able to repro this issue ([here's my test](http://jsbin.com/dokawuq/edit?html,console,output)). What type is the `location` property of your items? Any other info you can share?

**Comment by vinhtq** [comment]
Sorry! This is really really weird for me also.

This code i rewrite to match quite the same as my code:
http://jsbin.com/rivuhufeku/edit?html,console,output

Here is my code:
http://pastebin.com/5UkN972E

**Comment by bicknellr** [comment]
(@bicknellr self ping to look at this tomorrow)

**Comment by vinhtq** [comment]
Thanks and sorry if my stupidity wastes your time!

**Comment by bicknellr** [comment]
No! Always better to file than not.

**Comment by bicknellr** [comment]
Important prereq for using paper-listbox: you have to import paper-listbox! [:)](http://jsbin.com/qacace/edit?html,console,output) Let me know if this doesn't work / or if the import just didn't get pasted.

p.s. The suggestions-slideup closing tag is missing `/`.

**Comment by vinhtq** [comment]
Yeah, it is really my missing. Sorry for this!
