### ISSUE TITLE
Broken layout and style in Edge 40 (EdgeHTML 15)

### ISSUE THREAD

**Issue by feuerste** [PolymerElements/paper-listbox#39]
### Description
In the latest Edge 40.15063.0.0 from Windows 10 Creators Update, the layout and style of the `paper-listbox` is broken, also when used e.g. inside `paper-dropdown-menu`.

### Expected outcome
![paper-listbox-edge38](https://user-images.githubusercontent.com/362372/26969373-cf5ac91c-4d05-11e7-9b46-20df2e43f8af.png)
![paper-dropdown-menu-edge38](https://user-images.githubusercontent.com/362372/26969384-d4a47f44-4d05-11e7-8d77-160ffa9bee78.png)

### Actual outcome
![paper-listbox-edge40](https://user-images.githubusercontent.com/362372/26969498-3af0a99e-4d06-11e7-80e7-5fc9fb134bee.png)
![paper-dropdown-menu-edge40](https://user-images.githubusercontent.com/362372/26969519-4d4d123a-4d06-11e7-9c76-25c3274c8738.png)

### Live Demo
https://www.webcomponents.org/element/PolymerElements/paper-listbox/demo/demo/index.html
https://www.webcomponents.org/element/PolymerElements/paper-dropdown-menu/demo/demo/index.html

### Steps to reproduce
1. Download and install Windows 10 Creators Update from https://www.microsoft.com/en-us/software-download/windows10
2. Run any of the above live demos in Edge 40

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [x] Edge 40
- [ ] IE 11
- [ ] IE 10

**Comment by rediche** [comment]
I've noticed this too. It can be replicated on browserstack.com.

Edge 40 is running EdgeHTML 15 for clarification.

This was not broken on Edge 38 with EdgeHTML 14.

**Comment by rediche** [comment]
I've done some further research on this issue.

Edge 40 & EdgeHTML 15 seems to be causing a wide variety of styling issues across the board. 

Here is some similar cases:
* PolymerElements/paper-styles#144
* PolymerElements/paper-styles#145
* PolymerElements/paper-item#115

A way I've found to fix some of the issues of `paper-listbox`/`paper-item`/`paper-styles` is to go directly into `roboto.html` in the package font-roboto and add `type="text/css`. It does not fix all the issues, but some. The `paper-listbox` will be vertical again. Only issue I can see on that solution, is that the selected item "jumps around" on screen. I also have no idea how that fix actually works, so problem is probably to be found elsewhere. 

Overall it seems like the issues are going back to `paper-styles`, perhaps even Edge 40's support of CSS Custom Properties. It is already known that [Edge 40 has some issues](http://caniuse.com/#search=custom%20properties) with them.

**Comment by feuerste** [comment]
I just found a workaround for the items that are "jumping around". Edge 40 somehow sets the `position` of selected/focused elements from `relative` to `absolute`. By enforcing
```
paper-listbox ::slotted(*) {
  position: relative !important;
}
```
in a shared style file I could fix it throughout our application.
This should also work for PolymerElements/paper-styles#145 and PolymerElements/paper-item#115.

**Comment by feuerste** [comment]
I don't get the problems any more with webcomponentsjs 1.0.7, which uses shadycss 1.0.4, see also webcomponents/shadycss@74577b11f20442594cedf4c5a51152dca06eb67c and webcomponents/shadycss@58575e57c65aa0ff22a941129385122b2749a33e
