### ISSUE TITLE
Should the demo work out of the box, when repository cloned?

### ISSUE THREAD

**Issue by LoveAndHappiness** [PolymerElements/paper-listbox#5]
Hi there, 

Should the demo work out of the box, when repository cloned?

Right now it is necessary to change some paths in the `demo/index.html` so that the demo can be seen when cloned.

**Comment by mwtidd** [comment]
If you run a bower update and start up polyserve it seems to work fine.

[Create a Reusable Element](https://www.polymer-project.org/1.0/docs/start/reusableelements.html#develop-and-test)
