### ISSUE TITLE
paper-listbox not included in Paper Elements Bower update.

### ISSUE THREAD

**Issue by PaulHMason** [PolymerElements/paper-listbox#6]
Should the paper-listbox not be included in the Bower update? I'm assuming it will have it's own folder.

**Comment by JustinXinLiu** [comment]
+1

**Comment by abdonrd** [comment]
Added by @blasten!

https://github.com/PolymerElements/paper-elements/commit/ce7c011cd47dcbb450e4b2e3407913ca633473a3

**Comment by bicknellr** [comment]
Thanks for the link, @abdonrd.

**Comment by abdonrd** [comment]
@bicknellr your welcome! :+1
