### ISSUE TITLE
Use case vs paper-menu

### ISSUE THREAD

**Issue by zmoshansky** [PolymerElements/paper-listbox#7]
Could you explain or link to some relevant information about when to use this over paper-menu? 

The W3 Roles don't present a terrific differentiation. As I interpreted, a menu shouldn't have multi-select and activating items in a menu should cause an instant action?

[W3 Roles - #List](http://www.w3.org/TR/wai-aria/roles#listbox)
[W3 Roles - #Menu](http://www.w3.org/TR/wai-aria/roles#menu)

**Comment by moderndeveloperllc** [comment]
The last question of the most recent Polycast - [#33](https://www.youtube.com/watch?v=_VqeFubvNKw) addresses that with basically what you stated above - list is for multiselect and menu is single select.

**Comment by mercmobily** [comment]
For posterity...

This is my 2c ... I also left it as a comment to the Youtube video.

This is my own private list of differences between paper-menu and paper-listbox:

paper-menu:
- Comes with paper-menu-shared-styles
- Has paper-sub-menu
- Has extra styling option to make it disabled
- Has mixins for selected and focussed items

Also, both of them have the "multi" option, so I am not sure that's a huge difference.
Finally, the code is amazingly similar. I don't think I'd keep paper-listbox in the repo, frankly...﻿
